MQTT_BROKER_HOST = "broker.hivemq.com"
MQTT_BROKER_PORT = 1883

MQTT_BROKER_TOPIC_PREFIX = "iot/313357402/YY"
MQTT_COLLAR_TOPIC = f"{MQTT_BROKER_TOPIC_PREFIX}/collar"

MQTT_COLLAR_LOCATION_CLIENT_ID_PREFIX = "IOT_313357402_COLLAR_LOCATION"
